apiVersion: v1
kind: Service
metadata:
  labels:
    app: multivac
  name: multivac
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP 
  selector:
    app: multivac

